name: test_integration
publish_to: none
resolution: workspace
environment:
  sdk: ^3.6.0

dependencies:
  _discoveryapis_commons: any
  args: ^2.4.0
  async: ^2.8.2
  googleapis: any
  googleapis_auth: any
  http: ^1.0.0
  path: ^1.8.3
  shelf: ^1.2.0
  stack_trace: ^1.10.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^4.0.0
  test: ^1.16.0
