name: googleapis_generator_dependency
publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.3.1
  discoveryapis_generator: any
  http: ^1.0.0
  io: ^1.0.0
  path: ^1.9.1
  pool: ^1.5.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.4

dev_dependencies:
  pub_semver: ^2.2.0
