name: sample
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  googleapis:
    path: ../../generated/googleapis
  googleapis_auth: any

dependency_overrides:
  _discoveryapis_commons:
    path: ../../discoveryapis_commons
  dart_flutter_team_lints: ^3.0.0
