# Manually curated lists of which APIs should go into which packages, and which
# should be ignored.
packages:
  googleapis:
    version: 16.0.0
    repository: https://github.com/google/googleapis.dart/tree/master/generated/googleapis
    readme: resources/README.md
    license: resources/LICENSE
    changelog: resources/googleapis/CHANGELOG.md
    example: resources/googleapis/examples/main.dart
    mono_pkg: resources/googleapis/_mono_pkg.yaml
    resolution: workspace
    extraDevDependencies:
        googleapis_auth: '^2.0.0'
    apis:
      - abusiveexperiencereport:v1
      - acceleratedmobilepageurl:v1
      - accessapproval:v1
      - accesscontextmanager:v1
      - addressvalidation:v1
      - adexperiencereport:v1
      - admin:datatransfer_v1
      - admin:directory_v1
      - admin:reports_v1
      - admob:v1
      - adsense:v2
      - adsenseplatform:v1
      - advisorynotifications:v1
      - aiplatform:v1
      - airquality:v1
      - alloydb:v1
      - analytics:v3
      - analyticshub:v1
      - androiddeviceprovisioning:v1
      - androidenterprise:v1
      - androidmanagement:v1
      - androidpublisher:v3
      - apigateway:v1
      - apigee:v1
      - apigeeregistry:v1
      - apihub:v1
      - apikeys:v2
      - appengine:v1
      - apphub:v1
      - appsmarket:v2
      - areainsights:v1
      - artifactregistry:v1
      - assuredworkloads:v1
      - authorizedbuyersmarketplace:v1
      - backupdr:v1
      - baremetalsolution:v2
      - batch:v1
      - beyondcorp:v1
      - biglake:v1
      - bigquery:v2
      - bigqueryconnection:v1
      - bigquerydatapolicy:v1
      - bigquerydatapolicy:v2
      - bigquerydatatransfer:v1
      - bigqueryreservation:v1
      - bigtableadmin:v2
      - billingbudgets:v1
      - binaryauthorization:v1
      - blockchainnodeengine:v1
      - blogger:v3
      - books:v1
      - businessprofileperformance:v1
      - calendar:v3
      - certificatemanager:v1
      - chat:v1
      - chromemanagement:v1
      - chromepolicy:v1
      - chromeuxreport:v1
      - chromewebstore:v1.1
      - chromewebstore:v2
      - civicinfo:v2
      - classroom:v1
      - cloudasset:v1
      - cloudbilling:v1
      - cloudbuild:v1
      - cloudbuild:v2
      - cloudchannel:v1
      - cloudcommerceprocurement:v1
      - cloudcontrolspartner:v1
      - clouddeploy:v1
      - cloudfunctions:v1
      - cloudfunctions:v2
      - cloudidentity:v1
      - cloudkms:v1
      - cloudlocationfinder:v1
      - cloudprofiler:v2
      - cloudresourcemanager:v1
      - cloudresourcemanager:v2
      - cloudresourcemanager:v3
      - cloudscheduler:v1
      - cloudsearch:v1
      - cloudshell:v1
      - cloudsupport:v2
      - cloudtasks:v2
      - cloudtrace:v2
      - composer:v1
      - compute:v1
      - config:v1
      - connectors:v1
      - connectors:v2
      - contactcenterinsights:v1
      - container:v1
      - containeranalysis:v1
      - content:v2.1
      - contentwarehouse:v1
      - css:v1
      - customsearch:v1
      - datacatalog:v1
      - dataform:v1
      - datafusion:v1
      - datalineage:v1
      - datamanager:v1
      - datamigration:v1
      - datapipelines:v1
      - dataplex:v1
      - dataportability:v1
      - dataproc:v1
      - datastore:v1
      - datastream:v1
      - deploymentmanager:v2
      - developerconnect:v1
      - dfareporting:v3.5
      - dfareporting:v4
      - dfareporting:v5
      - dialogflow:v2
      - dialogflow:v3
      - digitalassetlinks:v1
      - discovery:v1
      - displayvideo:v2
      - displayvideo:v3
      - displayvideo:v4
      - dlp:v2
      - dns:v1
      - docs:v1
      - documentai:v1
      - domains:v1
      - doubleclickbidmanager:v2
      - doubleclicksearch:v2
      - drive:v2
      - drive:v3
      - driveactivity:v2
      - drivelabels:v2
      - essentialcontacts:v1
      - eventarc:v1
      - fcm:v1
      - file:v1
      - firebaseappcheck:v1
      - firebaseappdistribution:v1
      - firebaseapphosting:v1
      - firebasedataconnect:v1
      - firebasedynamiclinks:v1
      - firebasehosting:v1
      - firebaseml:v1
      - firebaserules:v1
      - firestore:v1
      - fitness:v1
      - forms:v1
      - games:v1
      - gamesConfiguration:v1configuration
      - gamesManagement:v1management
      - gkebackup:v1
      - gkehub:v1
      - gkehub:v2
      - gkeonprem:v1
      - gmail:v1
      - gmailpostmastertools:v1
      - groupsmigration:v1
      - groupssettings:v1
      - healthcare:v1
      - homegraph:v1
      - hypercomputecluster:v1
      - iam:v1
      - iam:v2
      - iamcredentials:v1
      - iap:v1
      - identitytoolkit:v1
      - identitytoolkit:v2
      - identitytoolkit:v3
      - ids:v1
      - indexing:v3
      - integrations:v1
      - jobs:v3
      - jobs:v4
      - keep:v1
      - kgsearch:v1
      - kmsinventory:v1
      - language:v1
      - language:v2
      - libraryagent:v1
      - licensing:v1
      - localservices:v1
      - logging:v2
      - looker:v1
      - managedidentities:v1
      - managedkafka:v1
      - manufacturers:v1
      - meet:v2
      - memcache:v1
      - merchantapi:accounts_v1
      - merchantapi:conversions_v1
      - merchantapi:datasources_v1
      - merchantapi:inventories_v1
      - merchantapi:issueresolution_v1
      - merchantapi:lfp_v1
      - merchantapi:notifications_v1
      - merchantapi:ordertracking_v1
      - merchantapi:products_v1
      - merchantapi:promotions_v1
      - merchantapi:quota_v1
      - merchantapi:reports_v1
      - metastore:v1
      - migrationcenter:v1
      - ml:v1
      - monitoring:v3
      - mybusinessaccountmanagement:v1
      - mybusinessbusinessinformation:v1
      - mybusinesslodging:v1
      - mybusinessnotifications:v1
      - mybusinessplaceactions:v1
      - mybusinessqanda:v1
      - mybusinessverifications:v1
      - netapp:v1
      - networkconnectivity:v1
      - networkmanagement:v1
      - networksecurity:v1
      - networkservices:v1
      - notebooks:v1
      - notebooks:v2
      - oauth2:v2
      - observability:v1
      - ondemandscanning:v1
      - oracledatabase:v1
      - orgpolicy:v2
      - osconfig:v1
      - osconfig:v2
      - oslogin:v1
      - pagespeedonline:v5
      - parallelstore:v1
      - parametermanager:v1
      - paymentsresellersubscription:v1
      - people:v1
      - places:v1
      - playcustomapp:v1
      - playintegrity:v1
      - policyanalyzer:v1
      - policysimulator:v1
      - policytroubleshooter:v1
      - policytroubleshooter:v3
      - pollen:v1
      - privateca:v1
      - publicca:v1
      - pubsub:v1
      - pubsublite:v1
      - rapidmigrationassessment:v1
      - readerrevenuesubscriptionlinking:v1
      - realtimebidding:v1
      - recaptchaenterprise:v1
      - recommender:v1
      - redis:v1
      - reseller:v1
      - retail:v2
      - run:v1
      - run:v2
      - runtimeconfig:v1
      - safebrowsing:v4
      - safebrowsing:v5
      - script:v1
      - searchconsole:v1
      - secretmanager:v1
      - securesourcemanager:v1
      - securitycenter:v1
      - securityposture:v1
      - serviceconsumermanagement:v1
      - servicecontrol:v1
      - servicecontrol:v2
      - servicedirectory:v1
      - servicemanagement:v1
      - servicenetworking:v1
      - serviceusage:v1
      - sheets:v4
      - siteVerification:v1
      - slides:v1
      - smartdevicemanagement:v1
      - solar:v1
      - spanner:v1
      - speech:v1
      - storage:v1
      - storagebatchoperations:v1
      - storagetransfer:v1
      - streetviewpublish:v1
      - sts:v1
      - tagmanager:v1
      - tagmanager:v2
      - tasks:v1
      - testing:v1
      - texttospeech:v1
      - tpu:v1
      - tpu:v2
      - trafficdirector:v2
      - trafficdirector:v3
      - transcoder:v1
      - translate:v3
      - travelimpactmodel:v1
      - vault:v1
      - verifiedaccess:v1
      - verifiedaccess:v2
      - versionhistory:v1
      - videointelligence:v1
      - vision:v1
      - vmmigration:v1
      - vmwareengine:v1
      - vpcaccess:v1
      - walletobjects:v1
      - webfonts:v1
      - webrisk:v1
      - websecurityscanner:v1
      - workflowexecutions:v1
      - workflows:v1
      - workloadmanager:v1
      - workspaceevents:v1
      - workstations:v1
      - youtube:v3
      - youtubeAnalytics:v2
      - youtubereporting:v1 # https://developers.google.com/youtube/reporting/v1/reports/

  googleapis_beta:
    version: 9.1.0-wip
    repository: https://github.com/google/googleapis.dart/tree/master/generated/googleapis_beta
    readme: resources/README.md
    license: resources/LICENSE
    changelog: resources/googleapis_beta/CHANGELOG.md
    mono_pkg: resources/googleapis_beta/_mono_pkg.yaml
    resolution: workspace
    apis:
    - adexchangebuyer2:v2beta1 # https://developers.google.com/ad-exchange/buyer-rest/guides/client-access/
    - alertcenter:v1beta1 # https://developers.google.com/admin-sdk/alertcenter/
    - analyticsadmin:v1alpha
    - analyticsadmin:v1beta
    - analyticsdata:v1beta
    - bigqueryconnection:v1beta1
    - clouderrorreporting:v1beta1 # https://cloud.google.com/error-reporting/
    - cloudsupport:v2beta
    - dataflow:v1b3 # https://cloud.google.com/dataflow/
    - datalabeling:v1beta1
    - datastream:v1alpha1
    - factchecktools:v1alpha1
    - fcmdata:v1beta1
    - firebase:v1beta1
    - firebaseappcheck:v1beta
    - firebasedatabase:v1beta
    - firebasestorage:v1beta
    - gkehub:v2alpha
    - prod_tt_sasportal:v1alpha1
    - recommendationengine:v1beta1
    - sasportal:v1alpha1
    - sqladmin:v1beta4
    - toolresults:v1beta3 # https://developers.google.com/cloud-test-lab/

skip_tests:
- chat:v1 # generates classes that are too big to JSON encode/decode

# APIs that we do not wish to include in this package
skipped_apis:
  - admob:v1beta
  - adsenseplatform:v1alpha
  - aiplatform:v1beta1
  - alloydb:v1alpha
  - alloydb:v1beta
  - analyticsadmin:v1alpha
  - analyticshub:v1beta1
  - apigateway:v1beta
  - apim:v1alpha
  - appengine:v1alpha
  - appengine:v1beta
  - apphub:v1alpha
  - artifactregistry:v1beta1
  - artifactregistry:v1beta2
  - assuredworkloads:v1beta1
  - authorizedbuyersmarketplace:v1alpha
  - authorizedbuyersmarketplace:v1beta
  - beyondcorp:v1alpha
  - billingbudgets:v1beta1
  - binaryauthorization:v1beta1
  - checks:v1alpha
  - cloudasset:v1beta1
  - cloudasset:v1p1beta1
  - cloudasset:v1p5beta1
  - cloudasset:v1p7beta1
  - cloudbilling:v1beta
  - cloudcontrolspartner:v1beta
  - cloudfunctions:v2alpha
  - cloudfunctions:v2beta
  - cloudidentity:v1beta1
  - cloudlocationfinder:v1alpha
  - cloudresourcemanager:v1beta1
  - cloudresourcemanager:v2beta1
  - cloudscheduler:v1beta1
  - cloudtasks:v2beta2
  - cloudtasks:v2beta3
  - cloudtrace:v1
  - cloudtrace:v2beta1
  - composer:v1beta1
  - compute:alpha
  - compute:beta
  - contactcenteraiplatform:v1alpha1
  - container:v1beta1
  - containeranalysis:v1alpha1
  - containeranalysis:v1beta1
  - datacatalog:v1beta1
  - dataform:v1beta1
  - datafusion:v1beta1
  - datamigration:v1beta1
  - dataportability:v1beta
  - datastore:v1beta1
  - datastore:v1beta3
  - deploymentmanager:alpha
  - deploymentmanager:v2beta
  - dialogflow:v2beta1
  - dialogflow:v3beta1
  - discoveryengine:v1
  - discoveryengine:v1alpha
  - discoveryengine:v1beta
  - dns:v1beta2
  - documentai:v1beta3
  - domains:v1alpha2
  - domains:v1beta1
  - drivelabels:v2beta
  - file:v1beta1
  - firebaseappdistribution:v1alpha
  - firebaseapphosting:v1beta
  - firebasedataconnect:v1beta
  - firebasehosting:v1beta1
  - firebaseml:v1beta2
  - firebaseml:v2beta
  - firestore:v1beta1
  - firestore:v1beta2
  - gkehub:v1alpha
  - gkehub:v1beta
  - gkehub:v1beta1
  - gkehub:v2beta
  - gmailpostmastertools:v1beta1
  - healthcare:v1beta1
  - iam:v2beta
  - iap:v1beta1
  - identitytoolkit:v1
  - identitytoolkit:v2
  - jobs:v3p1beta1
  - language:v1beta2
  - managedidentities:v1alpha1
  - managedidentities:v1beta1
  - marketingplatformadmin:v1alpha
  - memcache:v1beta2
  - merchantapi:accounts_v1beta
  - merchantapi:conversions_v1beta
  - merchantapi:datasources_v1beta
  - merchantapi:inventories_v1beta
  - merchantapi:issueresolution_v1beta
  - merchantapi:lfp_v1beta
  - merchantapi:notifications_v1beta
  - merchantapi:ordertracking_v1beta
  - merchantapi:products_v1beta
  - merchantapi:promotions_v1beta
  - merchantapi:quota_v1beta
  - merchantapi:reports_v1beta
  - merchantapi:reviews_v1beta
  - metastore:v1alpha
  - metastore:v1beta
  - migrationcenter:v1alpha1
  - monitoring:v1
  - netapp:v1beta1
  - networkconnectivity:v1alpha1
  - networkmanagement:v1beta1
  - networksecurity:v1beta1
  - networkservices:v1beta1
  - ondemandscanning:v1beta1
  - osconfig:v1alpha
  - osconfig:v1beta
  - osconfig:v2beta
  - oslogin:v1alpha
  - oslogin:v1beta
  - parallelstore:v1beta
  - playdeveloperreporting:v1alpha1
  - playdeveloperreporting:v1beta1
  - playgrouping:v1alpha1
  - policyanalyzer:v1beta1
  - policysimulator:v1alpha
  - policysimulator:v1beta
  - policytroubleshooter:v1beta
  - policytroubleshooter:v3beta
  - privateca:v1beta1
  - publicca:v1alpha1
  - publicca:v1beta1
  - pubsub:v1beta1a
  - pubsub:v1beta2
  - recommender:v1beta1
  - redis:v1beta1
  - retail:v2alpha
  - retail:v2beta
  - runtimeconfig:v1beta1
  - saasservicemgmt:v1beta1
  - searchads360:v0
  - secretmanager:v1beta1
  - secretmanager:v1beta2
  - securitycenter:v1beta1
  - securitycenter:v1beta2
  - serviceconsumermanagement:v1beta1
  - servicedirectory:v1beta1
  - servicenetworking:v1beta
  - serviceusage:v1beta1
  - speech:v1p1beta1
  - sqladmin:v1
  - sts:v1beta
  - texttospeech:v1beta1
  - threatintelligence:v1beta
  - tpu:v1alpha1
  - tpu:v2alpha1
  - translate:v2
  - translate:v3beta1
  - videointelligence:v1beta2
  - videointelligence:v1p1beta1
  - videointelligence:v1p2beta1
  - videointelligence:v1p3beta1
  - vision:v1p1beta1
  - vision:v1p2beta1
  - vmmigration:v1alpha1
  - vpcaccess:v1beta1
  - websecurityscanner:v1alpha
  - websecurityscanner:v1beta
  - workflowexecutions:v1beta
  - workflows:v1beta
  - workstations:v1beta
