# Manually curated lists of which APIs should go into which packages, and which
# should be ignored.
packages:
- googleapis:
    version: 16.0.0-wip
    repository: https://github.com/google/googleapis.dart/tree/master/generated/googleapis
    readme: resources/README.md
    license: resources/LICENSE
    changelog: resources/googleapis/CHANGELOG.md
    example: resources/googleapis/examples/main.dart
    mono_pkg: resources/googleapis/_mono_pkg.yaml
    resolution: workspace
    extraDevDependencies:
        googleapis_auth: '^2.0.0'
    apis:
    - abusiveexperiencereport:v1 # https://developers.google.com/abusive-experience-report/
    - acceleratedmobilepageurl:v1 # https://developers.google.com/amp/cache/
    - accessapproval:v1
    - accesscontextmanager:v1
    - addressvalidation:v1
    - adexperiencereport:v1 # https://developers.google.com/ad-experience-report/
    - admin:datatransfer_v1 # https://developers.google.com/admin-sdk/data-transfer/
    - admin:directory_v1 # https://developers.google.com/admin-sdk/directory/
    - admin:reports_v1 # https://developers.google.com/admin-sdk/reports/
    - admob:v1
    - adsense:v2
    - adsenseplatform:v1
    - advisorynotifications:v1
    - aiplatform:v1
    - airquality:v1
    - alloydb:v1
    - analytics:v3 # https://developers.google.com/analytics/
    - analyticshub:v1
    - androiddeviceprovisioning:v1 # https://developers.google.com/zero-touch/
    - androidenterprise:v1 # https://developers.google.com/api-client-library/java/apis/androidenterprise/v1
    - androidmanagement:v1 # https://developers.google.com/android/management
    - androidpublisher:v3 # https://developers.google.com/android-publisher/
    - apigateway:v1
    - apigee:v1
    - apigeeregistry:v1
    - apihub:v1
    - apikeys:v2
    - appengine:v1 # https://cloud.google.com/appengine/docs/admin-api/
    - apphub:v1
    - appsmarket:v2
    - areainsights:v1
    - artifactregistry:v1
    - assuredworkloads:v1
    - authorizedbuyersmarketplace:v1
    - backupdr:v1
    - baremetalsolution:v2
    - batch:v1
    - beyondcorp:v1
    - biglake:v1
    - bigquery:v2 # https://developers.google.com/bigquery/
    - bigqueryconnection:v1
    - bigquerydatapolicy:v1
    - bigquerydatapolicy:v2
    - bigquerydatatransfer:v1 # https://cloud.google.com/bigquery/transfer/
    - bigqueryreservation:v1
    - bigtableadmin:v2 # https://cloud.google.com/bigtable/
    - billingbudgets:v1
    - binaryauthorization:v1
    - blockchainnodeengine:v1
    - blogger:v3 # https://developers.google.com/blogger/
    - books:v1 # https://developers.google.com/books/
    - businessprofileperformance:v1
    - calendar:v3 # https://developers.google.com/google-apps/calendar/
    - certificatemanager:v1
    - chat:v1 # https://developers.google.com/hangouts/chat
    - chromemanagement:v1
    - chromepolicy:v1
    - chromeuxreport:v1
    - chromewebstore:v1.1
    - chromewebstore:v2
    - civicinfo:v2 # https://developers.google.com/civic-information/
    - classroom:v1 # https://developers.google.com/classroom/
    - cloudasset:v1
    - cloudbilling:v1 # https://cloud.google.com/billing/
    - cloudbuild:v1 # https://cloud.google.com/container-builder/docs/
    - cloudbuild:v2
    - cloudchannel:v1
    - cloudcommerceprocurement:v1
    - cloudcontrolspartner:v1
    - clouddeploy:v1
    - cloudfunctions:v1 # https://cloud.google.com/functions/docs/
    - cloudfunctions:v2
    - cloudidentity:v1 # https://cloud.google.com/identity/
    - cloudkms:v1 # https://cloud.google.com/kms/docs/
    - cloudlocationfinder:v1
    - cloudprofiler:v2 # https://cloud.google.com/profiler/
    - cloudresourcemanager:v1 # https://cloud.google.com/resource-manager/
    - cloudresourcemanager:v2 # https://cloud.google.com/resource-manager/
    - cloudresourcemanager:v3
    - cloudscheduler:v1
    - cloudsearch:v1 # https://gsuite.google.com/products/cloud-search/
    - cloudshell:v1 # https://cloud.google.com/shell/docs/
    - cloudsupport:v2
    - cloudtasks:v2
    - cloudtrace:v2 # https://cloud.google.com/cloud-trace/
    - composer:v1 # https://cloud.google.com/composer/
    - compute:v1 # https://developers.google.com/compute/
    - config:v1
    - connectors:v1
    - connectors:v2
    - contactcenterinsights:v1
    - container:v1 # https://cloud.google.com/container-engine/
    - containeranalysis:v1
    - content:v2.1 # https://developers.google.com/shopping-content/
    - contentwarehouse:v1
    - css:v1
    - customsearch:v1 # https://developers.google.com/custom-search/
    - datacatalog:v1
    - dataform:v1
    - datafusion:v1
    - datalineage:v1
    - datamanager:v1
    - datamigration:v1
    - datapipelines:v1
    - dataplex:v1
    - dataportability:v1
    - dataproc:v1 # https://cloud.google.com/dataproc/
    - datastore:v1 # https://developers.google.com/datastore/
    - datastream:v1
    - deploymentmanager:v2 # https://cloud.google.com/deployment-manager/
    - developerconnect:v1
    - dfareporting:v3.5
    - dfareporting:v4
    - dfareporting:v5
    - dialogflow:v2 # https://cloud.google.com/dialogflow-enterprise/
    - dialogflow:v3 # https://cloud.google.com/dialogflow-enterprise/
    - digitalassetlinks:v1 # https://developers.google.com/digital-asset-links/
    - discovery:v1 # https://developers.google.com/discovery/
    - displayvideo:v2
    - displayvideo:v3
    - displayvideo:v4
    - dlp:v2 # https://cloud.google.com/dlp/
    - dns:v1 # https://cloud.google.com/dns/api/v1/
    - docs:v1
    - documentai:v1
    - domains:v1
    - doubleclickbidmanager:v2
    - doubleclicksearch:v2 # https://developers.google.com/doubleclick-search/
    - drive:v2 # https://developers.google.com/drive/v2/reference/
    - drive:v3 # https://developers.google.com/drive/v3/reference/
    - driveactivity:v2 # https://developers.google.com/drive/activity/
    - drivelabels:v2
    - essentialcontacts:v1
    - eventarc:v1
    - fcm:v1
    - file:v1
    - firebaseappcheck:v1
    - firebaseappdistribution:v1
    - firebaseapphosting:v1
    - firebasedataconnect:v1
    - firebasedynamiclinks:v1 # https://firebase.google.com/docs/dynamic-links/
    - firebasehosting:v1
    - firebaseml:v1
    - firebaserules:v1 # https://firebase.google.com/docs/storage/security/start
    - firestore:v1 # https://cloud.google.com/firestore
    - fitness:v1 # https://developers.google.com/fitness/
    - forms:v1
    - games:v1 # https://developers.google.com/games/services/
    - gamesConfiguration:v1configuration # https://developers.google.com/games/services/publishing/api/
    - gamesManagement:v1management # https://developers.google.com/games/services/management/api/
    - gkebackup:v1
    - gkehub:v1
    - gkehub:v2
    - gkeonprem:v1
    - gmail:v1 # https://developers.google.com/gmail/
    - gmailpostmastertools:v1
    - groupsmigration:v1 # https://developers.google.com/admin-sdk/groups-migration/
    - groupssettings:v1 # https://developers.google.com/admin-sdk/groups-settings/
    - healthcare:v1
    - homegraph:v1
    - hypercomputecluster:v1
    - iam:v1 # https://cloud.google.com/iam/
    - iam:v2
    - iamcredentials:v1 # https://cloud.google.com/iam/docs/creating-short-lived-service-account-credentials
    - iap:v1 # https://cloud.google.com/iap
    - identitytoolkit:v1 # https://cloud.google.com/identity-platform/docs/apis/
    - identitytoolkit:v2 # https://cloud.google.com/identity-platform/docs/apis/
    - identitytoolkit:v3 # https://developers.google.com/identity-toolkit/
    - ids:v1
    - indexing:v3 # https://developers.google.com/search/apis/indexing-api/
    - integrations:v1
    - jobs:v3 # https://cloud.google.com/job-discovery/docs
    - jobs:v4
    - keep:v1
    - kgsearch:v1 # https://developers.google.com/knowledge-graph/
    - kmsinventory:v1
    - language:v1 # https://cloud.google.com/natural-language/
    - language:v2 # https://cloud.google.com/natural-language/
    - libraryagent:v1 # https://cloud.google.com/docs/quota
    - licensing:v1 # https://developers.google.com/admin-sdk/licensing/v1/how-tos/using
    - localservices:v1
    - logging:v2 # https://cloud.google.com/logging/docs/
    - looker:v1
    - managedidentities:v1
    - managedkafka:v1
    - manufacturers:v1 # https://developers.google.com/manufacturers/
    - meet:v2
    - memcache:v1
    - merchantapi:accounts_v1
    - merchantapi:conversions_v1
    - merchantapi:datasources_v1
    - merchantapi:inventories_v1
    - merchantapi:issueresolution_v1
    - merchantapi:lfp_v1
    - merchantapi:notifications_v1
    - merchantapi:ordertracking_v1
    - merchantapi:products_v1
    - merchantapi:promotions_v1
    - merchantapi:quota_v1
    - merchantapi:reports_v1
    - metastore:v1
    - migrationcenter:v1
    - ml:v1 # https://cloud.google.com/ml-engine/
    - monitoring:v3 # https://cloud.google.com/monitoring/api/
    - mybusinessaccountmanagement:v1
    - mybusinessbusinessinformation:v1
    - mybusinesslodging:v1
    - mybusinessnotifications:v1
    - mybusinessplaceactions:v1
    - mybusinessqanda:v1
    - mybusinessverifications:v1
    - netapp:v1
    - networkconnectivity:v1
    - networkmanagement:v1
    - networksecurity:v1
    - networkservices:v1
    - notebooks:v1
    - notebooks:v2
    - oauth2:v2 # Note: this is used many places and sometimes the document is missing
    - observability:v1
    - ondemandscanning:v1
    - oracledatabase:v1
    - orgpolicy:v2
    - osconfig:v1
    - osconfig:v2
    - oslogin:v1 # https://cloud.google.com/compute/docs/oslogin/rest/
    - pagespeedonline:v5 # https://developers.google.com/speed/docs/insights/about
    - parallelstore:v1
    - parametermanager:v1
    - paymentsresellersubscription:v1
    - people:v1 # https://developers.google.com/people/
    - places:v1
    - playcustomapp:v1 # https://developers.google.com/android/work/play/custom-app-api
    - playintegrity:v1
    - policyanalyzer:v1
    - policysimulator:v1
    - policytroubleshooter:v1
    - policytroubleshooter:v3
    - pollen:v1
    - privateca:v1
    - publicca:v1
    - pubsub:v1 # https://cloud.google.com/pubsub/
    - pubsublite:v1
    - rapidmigrationassessment:v1
    - readerrevenuesubscriptionlinking:v1
    - realtimebidding:v1
    - recaptchaenterprise:v1
    - recommender:v1
    - redis:v1 # https://cloud.google.com/memorystore/docs/redis/
    - reseller:v1 # https://developers.google.com/admin-sdk/reseller/
    - retail:v2
    - run:v1
    - run:v2
    - runtimeconfig:v1 # https://cloud.google.com/deployment-manager/runtime-configurator/
    - safebrowsing:v4 # https://developers.google.com/safe-browsing/
    - safebrowsing:v5
    - script:v1 # https://developers.google.com/apps-script/execution/rest/v1/run
    - searchconsole:v1 # https://developers.google.com/webmaster-tools/search-console-api/
    - secretmanager:v1
    - securesourcemanager:v1
    - securitycenter:v1
    - securityposture:v1
    - serviceconsumermanagement:v1 # https://cloud.google.com/service-consumer-management/docs/overview
    - servicecontrol:v1 # https://cloud.google.com/service-control/
    - servicecontrol:v2
    - servicedirectory:v1
    - servicemanagement:v1 # https://cloud.google.com/service-management/
    - servicenetworking:v1
    - serviceusage:v1 # https://cloud.google.com/service-usage/
    - sheets:v4 # https://developers.google.com/sheets/reference/rest/
    - siteVerification:v1 # https://developers.google.com/site-verification/
    - slides:v1 # https://developers.google.com/slides/
    - smartdevicemanagement:v1
    - solar:v1
    - spanner:v1 # https://cloud.google.com/spanner/docs/
    - speech:v1 # https://cloud.google.com/speech/
    - storage:v1 # https://developers.google.com/storage/
    - storagebatchoperations:v1
    - storagetransfer:v1 # https://cloud.google.com/storage/transfer/
    - streetviewpublish:v1 # https://developers.google.com/streetview/publish/
    - sts:v1
    - tagmanager:v1 # https://developers.google.com/tag-manager/
    - tagmanager:v2 # https://developers.google.com/tag-manager/
    - tasks:v1 # https://developers.google.com/google-apps/tasks/
    - testing:v1 # https://developers.google.com/cloud-test-lab/
    - texttospeech:v1 # https://cloud.google.com/text-to-speech/
    - tpu:v1 # https://cloud.google.com/tpu/
    - tpu:v2
    - trafficdirector:v2
    - trafficdirector:v3
    - transcoder:v1
    - translate:v3
    - travelimpactmodel:v1
    - vault:v1 # https://apps.google.com/products/vault/
    - verifiedaccess:v1
    - verifiedaccess:v2
    - versionhistory:v1
    - videointelligence:v1 # https://cloud.google.com/video-intelligence/
    - vision:v1 # https://cloud.google.com/vision/reference/rest/
    - vmmigration:v1
    - vmwareengine:v1
    - vpcaccess:v1
    - walletobjects:v1
    - webfonts:v1 # https://developers.google.com/fonts/docs/developer_api
    - webrisk:v1
    - websecurityscanner:v1
    - workflowexecutions:v1
    - workflows:v1
    - workloadmanager:v1
    - workspaceevents:v1
    - workstations:v1
    - youtube:v3 # https://developers.google.com/youtube/
    - youtubeAnalytics:v2 # https://developers.google.com/youtube/analytics/
    - youtubereporting:v1 # https://developers.google.com/youtube/reporting/v1/reports/

- googleapis_beta:
    version: 9.1.0-wip
    repository: https://github.com/google/googleapis.dart/tree/master/generated/googleapis_beta
    readme: resources/README.md
    license: resources/LICENSE
    changelog: resources/googleapis_beta/CHANGELOG.md
    mono_pkg: resources/googleapis_beta/_mono_pkg.yaml
    resolution: workspace
    apis:
    - adexchangebuyer2:v2beta1 # https://developers.google.com/ad-exchange/buyer-rest/guides/client-access/
    - alertcenter:v1beta1 # https://developers.google.com/admin-sdk/alertcenter/
    - analyticsadmin:v1alpha
    - analyticsadmin:v1beta
    - analyticsdata:v1beta
    - bigqueryconnection:v1beta1
    - clouderrorreporting:v1beta1 # https://cloud.google.com/error-reporting/
    - cloudsupport:v2beta
    - dataflow:v1b3 # https://cloud.google.com/dataflow/
    - datalabeling:v1beta1
    - datastream:v1alpha1
    - factchecktools:v1alpha1
    - fcmdata:v1beta1
    - firebase:v1beta1
    - firebaseappcheck:v1beta
    - firebasedatabase:v1beta
    - firebasestorage:v1beta
    - gkehub:v2alpha
    - prod_tt_sasportal:v1alpha1
    - recommendationengine:v1beta1
    - sasportal:v1alpha1
    - sqladmin:v1beta4
    - toolresults:v1beta3 # https://developers.google.com/cloud-test-lab/

skip_tests:
- chat:v1 # generates classes that are too big to JSON encode/decode

# APIs that we do not wish to include in this package
skipped_apis:
- admob:v1beta #v1 included
- adsenseplatform:v1alpha
- aiplatform:v1beta1
- alloydb:v1alpha
- alloydb:v1beta
- analyticsadmin:v1alpha
- analyticshub:v1beta1
- apigateway:v1beta # v1 included
- apim:v1alpha
- appengine:v1alpha # v1 included
- appengine:v1beta
- apphub:v1alpha
- artifactregistry:v1beta1 #v1 included
- artifactregistry:v1beta2 #v1 included
- assuredworkloads:v1beta1
- authorizedbuyersmarketplace:v1alpha
- authorizedbuyersmarketplace:v1beta
- beyondcorp:v1alpha
- billingbudgets:v1beta1 # v1 included
- binaryauthorization:v1beta1 # v1 included
- checks:v1alpha
- cloudasset:v1beta1
- cloudasset:v1p1beta1 # v1 included
- cloudasset:v1p5beta1 # v1 included
- cloudasset:v1p7beta1 # v1 included
- cloudbilling:v1beta
- cloudcontrolspartner:v1beta
- cloudfunctions:v2alpha # v2beta included
- cloudfunctions:v2beta
- cloudidentity:v1beta1 # v1 included
- cloudlocationfinder:v1alpha
- cloudresourcemanager:v1beta1 # v1 included
- cloudresourcemanager:v2beta1 # v2 included
- cloudscheduler:v1beta1
- cloudtasks:v2beta2 # v2beta3 included
- cloudtasks:v2beta3
- cloudtrace:v1 # v2 included
- cloudtrace:v2beta1 # v2 included
- composer:v1beta1 # v1 included
- compute:alpha # v1 included
- compute:beta # v1 included
- contactcenteraiplatform:v1alpha1
- container:v1beta1 # v1 included
- containeranalysis:v1alpha1 # v1beta1 included
- containeranalysis:v1beta1 # https://cloud.google.com/container-registry/docs/reference/rest/
- datacatalog:v1beta1
- dataform:v1beta1
- datafusion:v1beta1 # v1 included
- datamigration:v1beta1
- dataportability:v1beta
- datastore:v1beta1 # v1 included
- datastore:v1beta3 # v1 included
- deploymentmanager:alpha # v2beta # v1 included
- deploymentmanager:v2beta # v1 included
- dialogflow:v2beta1 # v2 included
- dialogflow:v3beta1 # v3 included
- discoveryengine:v1 # https://cloud.google.com/discovery-engine/media/docs
- discoveryengine:v1alpha
- discoveryengine:v1beta
- dns:v1beta2 # v1 included
- documentai:v1beta3
- domains:v1alpha2 # v1beta1 included
- domains:v1beta1
- drivelabels:v2beta
- file:v1beta1
- firebaseappdistribution:v1alpha
- firebaseapphosting:v1beta
- firebasedataconnect:v1beta
- firebasehosting:v1beta1 # v1 included
- firebaseml:v1beta2
- firebaseml:v2beta
- firestore:v1beta1 # v1 included
- firestore:v1beta2 # v1 included
- gkehub:v1alpha
- gkehub:v1beta
- gkehub:v1beta1
- gkehub:v2beta
- gmailpostmastertools:v1beta1 # v1 included
- healthcare:v1beta1 # v1 included
- iam:v2beta
- iap:v1beta1 # v1 included
- identitytoolkit:v1
- identitytoolkit:v2
- jobs:v3p1beta1 # v3 included
- language:v1beta2 # v1 included
- managedidentities:v1alpha1 # v1 included
- managedidentities:v1beta1 # v1 included
- marketingplatformadmin:v1alpha
- memcache:v1beta2 # v1 included
- merchantapi:accounts_v1beta
- merchantapi:conversions_v1beta
- merchantapi:datasources_v1beta
- merchantapi:inventories_v1beta
- merchantapi:issueresolution_v1beta
- merchantapi:lfp_v1beta
- merchantapi:notifications_v1beta
- merchantapi:ordertracking_v1beta
- merchantapi:products_v1beta
- merchantapi:promotions_v1beta
- merchantapi:quota_v1beta
- merchantapi:reports_v1beta
- merchantapi:reviews_v1beta
- metastore:v1alpha # v1beta included
- metastore:v1beta
- migrationcenter:v1alpha1
- monitoring:v1 # v3 included
- netapp:v1beta1
- networkconnectivity:v1alpha1
- networkmanagement:v1beta1 # v1 included
- networksecurity:v1beta1
- networkservices:v1beta1
- ondemandscanning:v1beta1
- osconfig:v1alpha
- osconfig:v1beta # v1 included
- osconfig:v2beta
- oslogin:v1alpha # v1 available
- oslogin:v1beta # v1 available
- parallelstore:v1beta
- playdeveloperreporting:v1alpha1
- playdeveloperreporting:v1beta1
- playgrouping:v1alpha1
- policyanalyzer:v1beta1
- policysimulator:v1alpha
- policysimulator:v1beta
- policytroubleshooter:v1beta # v1 included
- policytroubleshooter:v3beta
- privateca:v1beta1
- publicca:v1alpha1
- publicca:v1beta1
- pubsub:v1beta1a # v1beta1, v1bets2 and v1 included
- pubsub:v1beta2 # v1 included
- recommender:v1beta1 # v1 included
- redis:v1beta1 # v1 included
- retail:v2alpha # v2 included
- retail:v2beta # v2 included
- runtimeconfig:v1beta1 # v1 included
- saasservicemgmt:v1beta1
- searchads360:v0
- secretmanager:v1beta1 # v1 included
- secretmanager:v1beta2
- securitycenter:v1beta1 # v1 included
- securitycenter:v1beta2 # v1 included
- serviceconsumermanagement:v1beta1 # v1 included
- servicedirectory:v1beta1 # v1 included
- servicenetworking:v1beta # v1 included
- serviceusage:v1beta1 # v1 included
- speech:v1p1beta1 # v1 included
- sqladmin:v1 # empty!
- sts:v1beta #v1 included
- texttospeech:v1beta1 # v1 included
- threatintelligence:v1beta
- tpu:v1alpha1 # v1 included
- tpu:v2alpha1
- translate:v2 # v3 included
- translate:v3beta1 # v3 included
- videointelligence:v1beta2 # v1 included
- videointelligence:v1p1beta1 # v1 included
- videointelligence:v1p2beta1
- videointelligence:v1p3beta1
- vision:v1p1beta1 # v1 included
- vision:v1p2beta1 # v1 included
- vmmigration:v1alpha1
- vpcaccess:v1beta1
- websecurityscanner:v1alpha # v1 included
- websecurityscanner:v1beta # v1 included
- workflowexecutions:v1beta # v1 included
- workflows:v1beta # v1 included
- workstations:v1beta
