name: googleapis_auth
version: 2.1.0-wip
description: Obtain Access credentials for Google services using OAuth 2.0
repository: https://github.com/google/googleapis.dart/tree/master/googleapis_auth

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  crypto: ^3.0.0
  google_cloud: ^0.3.0
  google_identity_services_web: ^0.3.3
  http: ^1.2.2
  http_parser: ^4.0.0
  meta: ^1.15.0

dev_dependencies:
  # build_ dependencies allow debugging web tests using:
  #   `dart pub run build_runner serve test`
  build_runner: ^2.5.0
  build_test: ^3.0.0
  build_web_compilers: ^4.1.1
  test: ^1.25.9
  test_descriptor: ^2.0.2

false_secrets:
  - test/test_utils.dart
