name: discoveryapis_generator
version: 1.1.0-wip
description: Create API Client libraries based on the Discovery API Service.
repository: https://github.com/google/googleapis.dart/tree/master/discoveryapis_generator

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  _discoveryapis_commons: ^1.0.0
  args: ^2.5.0
  collection: ^1.19.0
  dart_style: ^3.0.0
  http: ^1.2.2
  meta: ^1.15.0
  path: ^1.9.1
  pub_semver: ^2.1.4
  source_helper: ^1.3.5
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.25.9

executables:
  discoveryapis_generator: generate
