name: discoveryapis_generator
version: 1.1.0-dev
description: Create API Client libraries based on the Discovery API Service.
repository: https://github.com/google/googleapis.dart/tree/master/discoveryapis_generator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  _discoveryapis_commons: ^1.0.0
  args: ^2.0.0
  dart_style: ^2.0.0
  http: ^0.13.0
  meta: ^1.2.4
  path: ^1.3.3
  yaml: ^3.0.0

dev_dependencies:
  test: ^1.0.0

executables:
  discoveryapis_generator: generate
