name: discoveryapis_generator
version: 0.9.16-dev
description: Create API Client libraries based on the Discovery API Service.
repository: https://github.com/dart-lang/discoveryapis_generator

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  _discoveryapis_commons: ^0.2.0
  args: ^1.0.0
  dart_style: ^1.0.7
  http: '>=0.11.1 <0.13.0'
  meta: ^1.2.4
  path: ^1.3.3
  yaml: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.0.0

executables:
  discoveryapis_generator: generate
