name: discoveryapis_generator
version: 1.1.0-wip
description: Create API Client libraries based on the Discovery API Service.
repository: https://github.com/google/googleapis.dart/tree/master/discoveryapis_generator

resolution: workspace
environment:
  sdk: ^3.5.0

dependencies:
  _discoveryapis_commons: ^1.0.0
  args: ^2.5.0
  collection: ^1.16.0
  dart_style: ^2.3.7
  http: ^1.0.0
  meta: ^1.2.4
  path: ^1.3.3
  source_helper: ^1.3.0
  yaml: ^3.0.0

dev_dependencies:
  test: ^1.0.0

executables:
  discoveryapis_generator: generate
