name: Health
on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  health:
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@main
    with:
      sdk: stable
      # GENERATED FILES
      ignore_license: 'generated/**,_test_package/**'
      # TOO BIG!
      ignore_changelog: 'generated/**'
      # TOO BIG!
      ignore_unuseddependencies: 'generated/**'
      # Not enabled for now
      upload_coverage: false
    permissions:
      pull-requests: write
