name: file_test_package
description: Pubspec used for unittesting of the discoveryapis_generator package.
publish_to: none
environment:
  sdk: '>=2.11.99 <3.0.0'

dependencies:
  _discoveryapis_commons: ^1.0.0
  http: any

dev_dependencies:
  pedantic: any

dependency_overrides:
  _discoveryapis_commons:
    path: ../discoveryapis_commons
