name: file_test_package
description: Pubspec used for unittesting of the discoveryapis_generator package.
publish_to: none
resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  _discoveryapis_commons: ^1.0.0
  http: any
